[project]
name = "diagnostics-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "deepeval[inspect]>=4.2.6",
    "deepteam>=1.0.9",
    "docx2txt>=0.9",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.5",
    "langchain-google-genai>=4.4.0",
    "langchain-openai>=1.6.6",
    "langchain-openrouter>=0.2.9",
    "langchain-postgres>=0.0.18",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=0.2.0",
    "langgraph-cli[inmem,inmemory]>=0.4.32",
    "langgraph-sdk>=0.4.5",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "psycopg>=3.3.6",
    "psycopg-pool>=3.3.3",
    "pydantic>=2.13.5",
    "pypdf>=6.19.0",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.2.3",
    "pywin32>=312",
    "unstructured>=0.27.8",
    "sentry-sdk>=2.0.0",
]
